language: php

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

## List all PHP versions to test with
php:
  - 7.4

matrix:
  fast_finish: true

## Install Dependencies
install:
  - composer self-update
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --prefer-dist --no-interaction

## Run test Scripts
script:
  - vendor/bin/phpunit Tests/
